### ISSUE TITLE
"Unable to create a signed JWT from the given configuration" bug

### ISSUE THREAD

**Issue by toscan** [chalasr/lexik-jwt-authentication-sandbox#14]
I cannot get any token ! I got a message error as soon as I call this : 
curl -X POST -H "Content-Type: application/json" http://localhost:8000/login_check -d '{"username":"johndoe","password":"test"}'

**Comment by kplaczek** [comment]
I had the same issue. Generate new `private.pem` and `public.pem`. Replace ones that are in config/jwt and you will be set. You can read about that in installation section [https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#installation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#installation)

**Comment by regisnew** [comment]
Thanks @kplaczek. This works for me.

**Comment by toscan** [comment]
Works for me too.

**Comment by chalasr** [comment]
Regenerated the versioned keys, should be all good now. I have no idea why it was needed though :/

**Comment by tchafack** [comment]
> Regenerated the versioned keys, should be all good now. I have no idea why it was needed though :/

For me, it was just because I didn't pay attention to the doc; I didn't change (to put my passphrase) the JWT_PASSPHRASE value in my conf.

**Comment by fghalati** [comment]
Thank you @duhamelstuff 
same for me ! :o)
