### ISSUE TITLE
"Unable to find the controller for path "/login_check". The route is wrongly configured."

### ISSUE THREAD

**Issue by FullStackAlex** [chalasr/lexik-jwt-authentication-sandbox#16]
Hello,
I am unable to retrieve the token via a POST request. I get this error message from Symfony:
"Unable to find the controller for path "/login_check". The route is wrongly configured."

Is it a bug or did I miss any steps? The DefaultController in /src contains only functions for handling api and register routes but not the login_check....

**Comment by mortenhartvig** [comment]
Had similar issue. Problem was two things for me (on Windows). Three things, if you didn't swich branch to flex.

First. My curl http post was not correct. It had to use doubble quotes for everything (invalid json exception thrown, json_decode returned NULL when single quotes)

You may try (if using Windows console):
`curl -X POST -H "Content-Type: application/json" http://localhost:8000/login_check -d "{\"username\":\"johndoe\",\"password\":\"test\"}"`
(in unix style bash, the example from readme works just fine, just not on windows)

Second:
I had to regenerate the SSL keys. Not sure why though, but it worked. Maybe it's a Windows or PHP 7.2 thing.  

A: Find the JWT_PASSPHRASE in the .env and .env.dist files in the project root. Re-use it when regenerating, or replace it with something else.

B: Regenerate the private.pem and public.pem files in the config/jwt folder.

If you have GIT on Windows, you may use that for openssl key generation. Right click the project root folder, and hit "Git bash here" (or open a git bash, and navigate to your project root. Then run the following, and answer the key passphrase questions with the same string as JWT_PASSPHRASE from above.

` winpty openssl genrsa -out config/jwt/private.pem -aes256 4096 && winpty openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem`

**Comment by FullStackAlex** [comment]
Hey, thank you for the detailed response! 
But I could setup my actual project and don't need the sandbox anymore...

**Comment by chalasr** [comment]
This error is either due to a security misconfiguration (bad firewall order, or access_control rules order), or to an invalid request (not valid `application/json` content-type and/or body).
Closing here
