### ISSUE TITLE
/login_check is not working in browser

### ISSUE THREAD

**Issue by habibun** [chalasr/lexik-jwt-authentication-sandbox#6]
I am getting  401 Unauthorized.

![screenshot from 2017-09-07 13 27 56_new](https://user-images.githubusercontent.com/5810350/30152299-7fea3528-93d4-11e7-8b21-9dec1303f6f7.png)

**Comment by chalasr** [comment]
Did you call `/register` with the same data beforehand?

**Comment by habibun** [comment]
yes, when I request using terminal or postman it's work.

**Comment by chalasr** [comment]
Please fork this repository and create a branch with enough code to reproduce your issue. LexikJWTAuthenticationBundle is widely used, this is clearly not a bug but a problem in the way you are using it.

**Comment by chalasr** [comment]
The `Content-Type` should be set to `application/json` instead of `x-www-formurlencoded`.

**Comment by habibun** [comment]
after set content-type to application/json.here what i have get

![screenshot from 2017-09-07 20-54-21](https://user-images.githubusercontent.com/5810350/30170525-2709f10e-9411-11e7-81ba-ea748aed6c02.png)

content-type show nothing.

here is my full code

```
fetch(APP_URL.APP_BACKEND_URL.BACKEND_SIGN_IN, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                "Content-type": "application/json"
            },
            body: JSON.stringify({
                "_username": this.state._username,
                "_password": this.state._password
            })
        })
```

**Comment by chalasr** [comment]
First screenshot uses localhost:8000 but this one uses `tcb.dev`, if you got it works with the PHP built-in webserver and not your own webserver (nginx, apache), then there is a problem in your environment. Nothing I can do here.
