### ISSUE TITLE
Can generate token but can't use it

### ISSUE THREAD

**Issue by acidjames** [chalasr/lexik-jwt-authentication-sandbox#7]
Hi, 

first of all thanks for creating this sandbox. I have sucessfully managed to create a user and get a token from the app. My setup is very basic (everything up to date).

I guess it's okay here to post a token as it's a demo...

Well, from this example you can see the token isn't found, even though it's just been created

```
 ~ curl -X POST http://localhost:8000/login_check -d _username=John -d _password=Doe                                                              
{"token":"eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6IkpvaG4iLCJleHAiOjE1MDk4MjUyNDIsImlhdCI6MTUwOTgyMTY0Mn0.r4FIFAyzDqPaxp2hsv2IOU_99tMGGHZ7uC8drGU2OW3EC_JRMcey2y7IhsiZuaWPSF23vyx49GCYAsn_gVw5jTR0lbC4lAzfitbV0sxKTG8PmEDXgKAKR7pOrSP24JwXxgWmeHTo0tDwXLm_RTNHvR3TDH5ob9HfUgFKzr3vcgV04v41wipb6Q1L-gW09vJXAI74q0GKCjQpgtnhC0kOcHaE7wWvwCRClLm-hHxfTdDdO5tphNHpnzHCIKeoYsfQ7_Wp36tBtzMN1XVuqkpSxr9Bn6wP9yKWE1-TGPKDT3Zo0UQ7Bw9epiMBrF1c4aGRiJDL3UnzFHUQxtalLupak7S6XyAjNQengOUjle7ktDtI7y-Pq1cJgEtZ8m0L8050Xr3rxgb74R-Y8dSJ2h_SXAO2Sz_Ow0MO5ajYRsrpfFGZwidBl17y_-uh1zKjCGwACy2wa0LTOt0spkYDe4EpghLDbvsAsO5KGSaxpo80mWtYl84AKTGV2HPrfg_iu5Uo29TnC1v2yEWD5GVChqzh2zsYeLUzFu6Nn50vHbli0yd0K8-ZrzDXnZpHP6yeFv1g8EESOrCUvJ_g41-KJ1mQzLeSJpUCRIARzBAWZj1YFUP6PmRT6THcK1rFrV-XDEcceZ7VkuXhp-lA7oPITEGy1lpw6jId4xavTFZS40km-pQ"}


~ curl http://localhost:8000/api -H "Authorization : Bearer eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6IkpvaG4iLCJleHAiOjE1MDk4MjUyNDIsImlhdCI6MTUwOTgyMTY0Mn0.r4FIFAyzDqPaxp2hsv2IOU_99tMGGHZ7uC8drGU2OW3EC_JRMcey2y7IhsiZuaWPSF23vyx49GCYAsn_gVw5jTR0lbC4lAzfitbV0sxKTG8PmEDXgKAKR7pOrSP24JwXxgWmeHTo0tDwXLm_RTNHvR3TDH5ob9HfUgFKzr3vcgV04v41wipb6Q1L-gW09vJXAI74q0GKCjQpgtnhC0kOcHaE7wWvwCRClLm-hHxfTdDdO5tphNHpnzHCIKeoYsfQ7_Wp36tBtzMN1XVuqkpSxr9Bn6wP9yKWE1-TGPKDT3Zo0UQ7Bw9epiMBrF1c4aGRiJDL3UnzFHUQxtalLupak7S6XyAjNQengOUjle7ktDtI7y-Pq1cJgEtZ8m0L8050Xr3rxgb74R-Y8dSJ2h_SXAO2Sz_Ow0MO5ajYRsrpfFGZwidBl17y_-uh1zKjCGwACy2wa0LTOt0spkYDe4EpghLDbvsAsO5KGSaxpo80mWtYl84AKTGV2HPrfg_iu5Uo29TnC1v2yEWD5GVChqzh2zsYeLUzFu6Nn50vHbli0yd0K8-ZrzDXnZpHP6yeFv1g8EESOrCUvJ_g41-KJ1mQzLeSJpUCRIARzBAWZj1YFUP6PmRT6THcK1rFrV-XDEcceZ7VkuXhp-lA7oPITEGy1lpw6jId4xavTFZS40km-pQ"

{"code":401,"message":"JWT Token not found"}
```

I really don't know how to debug this as i've been going straigt to the point, reading the doc, didn't change anything in the code...
Thanks in advance,

**Comment by llaville** [comment]
@acidjames Hello

I've just test it myself, and get the same issue. But if you look on source code https://github.com/chalasr/lexik-jwt-authentication-sandbox/blob/master/src/AppBundle/Security/Guard/JWTAuthenticator.php#L19 you will see that the Authorization header used the `JWT` prefix rather than `Bearer` as explained in README page.

The README page should be fixed.

Hope it will help !

**Comment by anjanasilva** [comment]
Also make sure that,

You have created ".htaccess" file in your public folder and have following code inside.

RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.)
RewriteRule . - [e=HTTP_AUTHORIZATION:%1]

https://stackoverflow.com/a/41723192/767625
