### ISSUE TITLE
README should be fixed

### ISSUE THREAD

**Issue by llaville** [chalasr/lexik-jwt-authentication-sandbox#8]
Hello,

As explained by issue #7, in `Security\Guard\JWTAuthenticator` implementation, the `JWT` prefix was used instead of `Bearer` as displayed in README page.

Replace 

Access a secured route:
```
$ curl -H "Authorization: Bearer [TOKEN]" http://localhost:8000/api
-> Logged in as johndoe
```
By 

Access a secured route:
```
$ curl -H "Authorization: JWT [TOKEN]" http://localhost:8000/api
-> Logged in as johndoe
```

**Comment by alvarotech** [comment]
Another improvement could be telling to do `composer install` before creating the database.

**Comment by chalasr** [comment]
Thanks for reporting guys, I'll address the open issues asap. PRs welcomed of course :)
