### ISSUE TITLE
JWT Token not found

### ISSUE THREAD

**Issue by zukko1** [chalasr/lexik-jwt-authentication-sandbox#9]
download and configure the project, register a user and request the token but when I use this token, it does not work and I answered this

{
     "code": 401,
     "message": "JWT Token not found"
}

**Comment by anjanasilva** [comment]
The solution to this is,  create ".htaccess" file in your public folder and place following code inside.

RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

[https://stackoverflow.com/a/41723192/767625](url)
